import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "FIXIE GARUDA TEMPEST ALLOY SMOOTH WELD",
      slug: "fixie-garuda-tempest-alloy-smooth-weld",
      category: "Bikes",
      description: "A high-performance bike designed for speed and agility.",
      images: [
        "/images/sample-products/p1-black.png",
        "/images/sample-products/p1-blue.png",
        "/images/sample-products/p1-red.png",
        "/images/sample-products/p1-green.png",
        "/images/sample-products/p1-grey.png",
      ],
      price: 59.99,
      brand: "Garuda",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "PROMAX PF-30 FIXIE FIXGEAR BIKE",
      slug: "promax-pf-30-fixie-fixgear-bike",
      category: "Bikes",
      description: "ALL NEW PROMAX PF-30 ALLOY FIXIE",
      images: [
        "/images/sample-products/p3-black.png",
        "/images/sample-products/p3-grey.png",
        "/images/sample-products/p3-yellow.png",
      ],
      price: 85.9,
      brand: "Promax",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "PROMAX PM16 MOUNTAIN BIKE MTB",
      slug: "promax-pm16-mountain-bike-mtb",
      category: "Bikes",
      description: "2024 The all new promax pm16",
      images: [
        "/images/sample-products/p3-black.png",
        "/images/sample-products/p3-grey.png",
        "/images/sample-products/p3-yellow.png",
      ],
      price: 99.95,
      brand: "Promax",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Promax PM10 26er MOUNTAIN BIKE",
      slug: "promax-pm10-26er-mountain-bike",
      category: "Bikes",
      description: "Promax PM10 26er Mountain Bike",
      images: [
        "/images/sample-products/p4-green.png",
        "/images/sample-products/p4-grey.png",
        "/images/sample-products/p4-orange.png",
        "/images/sample-products/p4-red.png",
        "/images/sample-products/p4-white.png",
      ],
      price: 39.95,
      brand: "Promax",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "TRINX M800 MTB",
      slug: "trinx-m800-mtb",
      category: "Bikes",
      description: "High-performance mountain bike for rugged terrains.",
      images: ["/images/sample-products/p5-gold.png"],
      price: 79.99,
      brand: "Trinx",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "TRINX M1000 QUEST AND ELITE MTB",
      slug: "trinx-m1000-quest-and-elite-mtb",
      category: "Bikes",
      description: "Versatile mountain bike for all terrains.",
      images: [
        "/images/sample-products/p6-27-5er.png",
        "/images/sample-products/p6-29er.png",
      ],
      price: 99.99,
      brand: "Trinx",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
